version: 0.1
phases:
  install:
    commands:
      - pip install chalice
      - pip install -r ${APP_NAME}/requirements.txt
      - cd ${APP_NAME} && chalice package /tmp/packaged
      - aws cloudformation package --template-file
        /tmp/packaged/sam.json --s3-bucket ${APP_S3_BUCKET}
        --output-template-file transformed.yaml
artifacts:
  type: zip
  files:
    - transformed.yaml
