version: 0.2

phases:
  pre_build:
    commands:
      - aws ssm get-parameter --with-decryption --name $BuildEnv --output text --query 'Parameter.Value' > /tmp/build_env.sh
      - source /tmp/build_env.sh
  build:
    commands:
      - sam build
  post_build:
    commands:
      # sam deploy
      - |
        sam deploy --stack-name $Env-$StackName --no-fail-on-empty-changeset --parameter-overrides \
            Env=$Env \
            ApiWafArn=$ApiWafArn \
            SchedulerExecutionRole=$SchedulerExecutionRole \
            LambdaExecutionRole=$LambdaExecutionRole
