AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  Sample SAM Template for sam-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  TestFunc:
    Type: AWS::Serverless::Function # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/
      Handler: app.handler
      Runtime: python3.10 # Supported Runtimes: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
      Architectures:
        - arm64 # x86_64 | arm64
      Role: arn:aws:iam::#AWS_ACCOUNT_ID:role/lambda_test
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref API
  TestFuncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TestFunc}
      RetentionInDays: 7

  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: test-api # A name for the API Gateway RestApi resource
      DisableExecuteApiEndpoint: true # Specifies whether clients can invoke your API by using the default execute-api endpoint.
      EndpointConfiguration:
        Type: REGIONAL # EDGE | REGIONAL | PRIVATE
      Domain:
        DomainName: api-test.tecotec.co.jp
        CertificateArn: arn:aws:acm:ap-northeast-1:965163745124:certificate/4b3a1be2-26c0-4831-8e80-a338d4ffa74e
        SecurityPolicy: TLS_1_2
        EndpointConfiguration: REGIONAL # REGIONAL | EDGE
        Route53:
          HostedZoneId: Z018056610BK6GVXLL29V
        BasePath: # List of stage name
          - v1
      Auth: # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html
        ResourcePolicy:
          IpRangeWhitelist:
            - 159.28.65.135
      StageName: v1
      AlwaysDeploy: false # Always deploys the API, even when no changes to the API have been detected.

