Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Parameter for getting the deployment environment
  # SecurityGroupIds:
#     Type: String
#     Description: Security Group Ids. Divided by comma
#   SubnetIds:
#     Type: String
#     Description: Subnet Ids. Divided by comma

Resources:
  Func0:
    Type: AWS::Serverless::Function # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: !Sub ${Env}-function-name
      Description: api function
      AutoPublishAlias: !Ref Env
      AutoPublishAliasAllProperties: true
      PackageType: Image
      ImageUri: 965163745124.dkr.ecr.ap-southeast-1.amazonaws.com/test:php-lambda-latest
      Role: arn:aws:iam::965163745124:role/LambdaExecutionRole
      Timeout: 60
      MemorySize: 128
  Func0LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Func0}
      RetentionInDays: 30
