Transform: AWS::Serverless-2016-10-31

# Parameters:
#   Env:
#     Type: String
#     Default: dev
#     Description: Parameter for getting the deployment environment
#   SecurityGroupIds:
#     Type: String
#     Description: Security Group Ids. Divided by comma
#   SubnetIds:
#     Type: String
#     Description: Subnet Ids. Divided by comma

Resources:
  # ScheduleFunctions:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./templates/ScheduleFunctions.yaml # 実際のテンプレート名に変更してください
  #     Parameters:
  #       Env: !Ref Env
  #       SecurityGroupId: !Ref SecurityGroupIds
  #       SubnetId1: !Ref SubnetIds
  APIs:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/APIs.yaml # 実際のテンプレート名に変更してください
      # Parameters:
      #   Env: !Ref Env
      #   SecurityGroupId: !Ref SecurityGroupIds
      #   SubnetId1: !Ref SubnetIds
  # HealthCareDxKonkeRegist:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./templates/HealthCareDxKonkeRegist.yaml # 実際のテンプレート名に変更してください
  #     Parameters:
  #       Env: !Ref Env
  #       RdsWriteEndpoint: !Ref RdsWriteEndpoint
  #       RdsWriteUser: !Ref RdsWriteUser
  #       RdsWritePassword: !Ref RdsWritePassword
  #       RdsReadEndpoint: !Ref RdsReadEndpoint
  #       RdsReadUser: !Ref RdsReadUser
  #       RdsReadPassword: !Ref RdsReadPassword
  # HealthCareDxLabeledDataAccumulating:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./templates/HealthCareDxLabeledDataAccumulating.yaml # 実際のテンプレート名に変更してください
  #     Parameters:
  #       Env: !Ref Env
  #       RdsWriteEndpoint: !Ref RdsWriteEndpoint
  #       RdsWriteUser: !Ref RdsWriteUser
  #       RdsWritePassword: !Ref RdsWritePassword
  #       RdsReadEndpoint: !Ref RdsReadEndpoint
  #       RdsReadUser: !Ref RdsReadUser
  #       RdsReadPassword: !Ref RdsReadPassword
  #       SecurityGroupId: !Ref SecurityGroupId
  #       SubnetId1: !Ref SubnetId1
  #       SubnetId2: !Ref SubnetId2
  #       SubnetId3: !Ref SubnetId3
  # HealthCareDXLabeling:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./templates/HealthCareDXLabeling.yaml # 実際のテンプレート名に変更してください
  #     Parameters:
  #       Env: !Ref Env
  #       RdsWriteEndpoint: !Ref RdsWriteEndpoint
  #       RdsWriteUser: !Ref RdsWriteUser
  #       RdsWritePassword: !Ref RdsWritePassword
  #       RdsReadEndpoint: !Ref RdsReadEndpoint
  #       RdsReadUser: !Ref RdsReadUser
  #       RdsReadPassword: !Ref RdsReadPassword
  #       ChildFuncArn: !GetAtt HealthCareDxLabeledDataAccumulating.Outputs.FuncArn
  # HealthCareDxExecution:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./templates/HealthCareDxExecution.yaml # 実際のテンプレート名に変更してください
  #     Parameters:
  #       Env: !Ref Env
  #       RdsWriteEndpoint: !Ref RdsWriteEndpoint
  #       RdsWriteUser: !Ref RdsWriteUser
  #       RdsWritePassword: !Ref RdsWritePassword
  #       RdsReadEndpoint: !Ref RdsReadEndpoint
  #       RdsReadUser: !Ref RdsReadUser
  #       RdsReadPassword: !Ref RdsReadPassword
  #       SecurityGroupId: !Ref SecurityGroupId
  #       SubnetId1: !Ref SubnetId1
  #       SubnetId2: !Ref SubnetId2
  #       SubnetId3: !Ref SubnetId3
  #       ChildFuncArn: !GetAtt HealthCareDXLabeling.Outputs.FuncArn
