AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  Sample SAM Template for sam-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  TestFunction:
    Type: AWS::Serverless::Function # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      AutoPublishAlias: dev
      AutoPublishAliasAllProperties: true
      CodeUri: functions/
      Handler: app.handler
      Runtime: python3.11 # Supported Runtimes: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
      Architectures:
        - arm64 # x86_64 | arm64
      Role: arn:aws:iam::#AWS_ACCOUNT_ID:role/lambda_test
      ReservedConcurrentExecutions: 1
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-northeast-1:965163745124:testQ
            BatchSize: 2
            Enabled: true
  TestFuncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TestFunction}
      RetentionInDays: 7
