Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Parameter for getting the deployment environment
  LambdaExecutionRole:
    Type: String
    Description: Service role arn for lambda functions.
  ApiWafArn:
    Type: String
    Description: WAF Arn for api gateway.
  SchedulerExecutionRole:
    Type: String
    Description: Excution Role ARN for scheduler.

Resources:
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/api.yaml
      Parameters:
        Env: !Ref Env
        LambdaExecutionRole: !Ref LambdaExecutionRole
        ApiWafArn: !Ref ApiWafArn
  Sqs:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/sqs.yaml
      Parameters:
        Env: !Ref Env
        LambdaExecutionRole: !Ref LambdaExecutionRole
  Schedule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/schedule.yaml
      Parameters:
        Env: !Ref Env
        LambdaExecutionRole: !Ref LambdaExecutionRole
        SchedulerExecutionRole: !Ref SchedulerExecutionRole
