Transform: AWS::Serverless-2016-10-31

# Globals: # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
#   Function:
#     Runtime: python3.11 # Supported Runtimes: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
#     Architectures:
#       - arm64 # x86_64 | arm64

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Parameter for getting the deployment environment
  # SecurityGroupIds:
#     Type: String
#     Description: Security Group Ids. Divided by comma
#   SubnetIds:
#     Type: String
#     Description: Subnet Ids. Divided by comma

Resources:
  Func0:
    Type: AWS::Serverless::Function # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: !Sub ${Env}-function-name
      Description: api function
      AutoPublishAlias: !Ref Env
      AutoPublishAliasAllProperties: true
      PackageType: Image
      ImageUri: 965163745124.dkr.ecr.ap-southeast-1.amazonaws.com/test:php-lambda-latest
      Role: arn:aws:iam::965163745124:role/LambdaExecutionRole
      Timeout: 60
      MemorySize: 128
      Architectures:
        - x86_64 # x86_64 | arm64
  Func0LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Func0}
      RetentionInDays: 30
  Func1:
    Type: AWS::Serverless::Function # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      Runtime: python3.11
      FunctionName: !Sub ${Env}-function-name1
      Description: api function
      AutoPublishAlias: !Ref Env
      AutoPublishAliasAllProperties: true
      CodeUri: ./functions
      Handler: app.handler
      Role: arn:aws:iam::965163745124:role/LambdaExecutionRole
      Timeout: 60
      MemorySize: 128
  Func1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Func1}
      RetentionInDays: 30
