AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sam-test
Globals: # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Runtime: python3.11 # Supported Runtimes: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
    Timeout: 10
    MemorySize: 128
    Architectures:
      - arm64 # x86_64 | arm64

Resources:
  Func0:
    Type: AWS::Serverless::Function # More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: Func1
      Description: SAM test function
      AutoPublishAlias: dev
      CodeUri: functions/
      Handler: app.handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_test
      ReservedConcurrentExecutions: 2
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref API
      VpcConfig:
        SecurityGroupIds:
          - sg-0f8969de0116a5cd0
        SubnetIds:
          - subnet-0d57575d8609fbdfb
          - subnet-07a24e72b6c10c9fb
  Func0LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Func0}
      RetentionInDays: 7

  ApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/APIGWtoCloudWatchLogs

  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: test-api # A name for the API Gateway RestApi resource
      OpenApiVersion: '3.0.1' # prevent auto create Stage
      DisableExecuteApiEndpoint: true # Specifies whether clients can invoke your API by using the default execute-api endpoint.
      EndpointConfiguration:
        Type: REGIONAL # EDGE | REGIONAL | PRIVATE
      Domain:
        DomainName: api-test.tecotec.co.jp
        CertificateArn: arn:aws:acm:ap-northeast-1:965163745124:certificate/4b3a1be2-26c0-4831-8e80-a338d4ffa74e
        SecurityPolicy: TLS_1_2
        EndpointConfiguration: REGIONAL # REGIONAL | EDGE
        Route53:
          HostedZoneId: Z018056610BK6GVXLL29V
        BasePath:
          - /
      StageName: dev
      AlwaysDeploy: false # Always deploys the API, even when no changes to the API have been detected.
      AccessLogSetting:
        DestinationArn: !GetAtt APILogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","extendedRequestId":"$context.extendedRequestId","sourceIp":"$context.identity.sourceIp","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLength":$context.responseLength,"responseLatency":$context.responseLatency,"apiGatewayErrorMessage":"$context.error.message"}'
      Auth:
        ApiKeyRequired: true
        UsagePlan: # More info https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiusageplan.html
          UsagePlanName: ForDev
          Description: Usage plan for this API
          CreateUsagePlan: PER_API # Valid values: PER_API, SHARED, and NONE .
  APILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/api-test.tecotec.co.jp
      RetentionInDays: 7

  # WAFAssociation:
  #   Type: AWS::WAFv2::WebACLAssociation
  #   DependsOn: APIStage # More info https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-specification-generated-resources-api.html
  #   Properties:
  #     ResourceArn: !Sub arn:partition:apigateway:${AWS::Region}::/restapis/${API}/stages/dev
  #     WebACLArn: arn:aws:wafv2:ap-northeast-1:965163745124:regional/webacl/test/83d7543d-725f-4b60-8ba1-ee95105be96b
