AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  Sample SAM Template for sam-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  sshKeyGenerateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      Role: arn:aws:iam::#AWS_ACCOUNT_ID:role/lambda_test
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: 'at(2023-09-07T17:00:00)'
            ScheduleExpressionTimezone: 'Asia/Tokyo'
            RoleArn: arn:aws:iam::#AWS_ACCOUNT_ID:role/EventBridgeServiceRole
