AWSTemplateFormatVersion: 2010-09-09
Description: test
Resources:
  ###
  ###---Resources:JobQueue---
  ###
  ComputeEnv:
    Type: 'AWS::Batch::ComputeEnvironment'
    Properties:
      Type: MANAGED
      ServiceRole: arn:aws:iam::965163745124:role/aws-service-role/batch.amazonaws.com/AWSServiceRoleForBatch
      ComputeEnvironmentName: cnfTestComputeEnv
      ComputeResources:
        MaxvCpus: 256
        SecurityGroupIds:
          - sg-0f8969de0116a5cd0
        Subnets:
          - subnet-0d57575d8609fbdfb
          - subnet-07a24e72b6c10c9fb
          - subnet-093a9f1b37f2e907e
        Type: FARGATE_SPOT # FARGATE | FARGATE_SPOT
      State: ENABLED
  ###
  ###---Resources:JobQueue---
  ###
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: cnfTestQ
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref ComputeEnv
      State: ENABLED
      Priority: 1
  ###
  ###---Resources:JobDefinition---
  ###
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      PlatformCapabilities:
        - FARGATE
      JobDefinitionName: cnfTest
      Timeout:
        AttemptDurationSeconds: 60
      ContainerProperties:
        Command: # `CMD` exec form
          - s3
          - ls
        ResourceRequirements:
          - Type: MEMORY # MEMORY | VCPU
            Value: '2048' # more info https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-resourcerequirement.html
          - Type: VCPU # MEMORY | VCPU
            Value: '1' # more info https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-resourcerequirement.html
        Image: public.ecr.aws/aws-cli/aws-cli:latest
        ExecutionRoleArn: arn:aws:iam::965163745124:role/ECSTaskExecutionRoleTest # for ECS create container. More info https://docs.aws.amazon.com/batch/latest/userguide/execution-IAM-role.html
        JobRoleArn: arn:aws:iam::965163745124:role/BatchJobRole # for containers. Like EC2 profile.
  ###
  ###---Resources:Scheduler---
  ###
  Scheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: cnfTestSchedule
      ## at expression - at(yyyy-MM-ddTHH:mm:ss)
      ## rate expression - rate(value unit) unit could be <minute | minutes | hour | hours | day | days>  example: rate(1 minute)
      ## cron expression - cron(fields) fields consists of six fields separated by white spaces <minutes hours day_of_month month day_of_week year>
      ScheduleExpression: rate(1 minutes)
      ScheduleExpressionTimezone: 'Asia/Tokyo'
      FlexibleTimeWindow:
        Mode: 'OFF'
      State: DISABLED # DISABLED | ENABLED
      Target:
        Arn: arn:aws:scheduler:::aws-sdk:batch:submitJob
        Input: '{ "JobDefinition": "cnfTest", "JobName": "cnfTestJob", "JobQueue": "cnfTestQ" }'
        RoleArn: arn:aws:iam::965163745124:role/EventSchedulerServiceRole
        RetryPolicy:
          MaximumRetryAttempts: 0
